### ISSUE TITLE
CpoAttribute - new type - Map

### ISSUE THREAD

**Issue by berryware** [cpo-org/cpo-api#11]
Create a new type for attributes for map support. This would basically contain a key/value pair of all attributes that the bean didn't have and would return them. this is extremely useful for cassandra where using dynamic columns.

David Berry 
2012-11-09
Need to add a new type to the JdbcMetaData class.
Need to make sure that cpoUtli can generate the correct class.

**Comment by mbellomo** [comment]
This is a duplicate of #24
